use [DEV-01]
GO

CREATE TABLE [Ingredients](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[IngredientName] [nvarchar](max) NOT NULL,
	[NormalizedName] [nvarchar](450) NOT NULL,
 CONSTRAINT [PK_Ingredients] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [Ingredients] ADD  DEFAULT (N'') FOR [NormalizedName]
GO

CREATE TABLE [Recipes](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[RecipeName] [nvarchar](max) NOT NULL,
	[RecipeDesc] [nvarchar](max) NULL,
 CONSTRAINT [PK_Recipes] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

CREATE TABLE [RecipeIngredients](
	[IngId] [int] IDENTITY(1,1) NOT NULL,
	[RecipeId] [int] NOT NULL,
	[IngredientNameModifier] [nvarchar](max) NULL,
	[Quantity] [float] NOT NULL,
	[QuantityDesc] [nvarchar](max) NULL,
	[IngredientId] [int] NOT NULL,
 CONSTRAINT [PK_RecipeIngredients] PRIMARY KEY CLUSTERED 
(
	[IngId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [RecipeIngredients]  WITH CHECK ADD  CONSTRAINT [FK_RecipeIngredients_Ingredients_IngredientId] FOREIGN KEY([IngredientId])
REFERENCES [Ingredients] ([Id])
ON DELETE CASCADE
GO

ALTER TABLE [RecipeIngredients] CHECK CONSTRAINT [FK_RecipeIngredients_Ingredients_IngredientId]
GO

ALTER TABLE [RecipeIngredients]  WITH CHECK ADD  CONSTRAINT [FK_RecipeIngredients_Recipes_RecipeId] FOREIGN KEY([RecipeId])
REFERENCES [Recipes] ([Id])
ON DELETE CASCADE
GO

ALTER TABLE [RecipeIngredients] CHECK CONSTRAINT [FK_RecipeIngredients_Recipes_RecipeId]
GO

CREATE TABLE [RecipeSteps](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[RecipeId] [int] NOT NULL,
	[Instruction] [nvarchar](max) NOT NULL,
 CONSTRAINT [PK_RecipeSteps] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [RecipeSteps]  WITH CHECK ADD  CONSTRAINT [FK_RecipeSteps_Recipes_RecipeId] FOREIGN KEY([RecipeId])
REFERENCES [Recipes] ([Id])
ON DELETE CASCADE
GO

ALTER TABLE [RecipeSteps] CHECK CONSTRAINT [FK_RecipeSteps_Recipes_RecipeId]
GO

CREATE TABLE [RecipeTags](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[RecipeId] [int] NOT NULL,
	[Tag] [nvarchar](max) NOT NULL,
 CONSTRAINT [PK_RecipeTags] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [RecipeTags]  WITH CHECK ADD  CONSTRAINT [FK_RecipeTags_Recipes_RecipeId] FOREIGN KEY([RecipeId])
REFERENCES [Recipes] ([Id])
ON DELETE CASCADE
GO

ALTER TABLE [RecipeTags] CHECK CONSTRAINT [FK_RecipeTags_Recipes_RecipeId]
GO
