<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>


  <ItemGroup>
    <SupportedPlatform Include="browser" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components" Version="9.0.18" />
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="9.0.10" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\v2\RecipeRecorder.Application\RecipeRecorder.Application.csproj" />
    <ProjectReference Include="..\v2\RecipeRecorder.Shared\RecipeRecorder.Shared.csproj" />
  </ItemGroup>

</Project>
